# Generated by Django 4.2 on 2023-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0003_alter_item_oprih_alter_item_postupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vydan',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
