# Generated by Django 4.2 on 2023-05-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0004_order_vydan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='state',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
