# Generated by Django 4.2 on 2023-05-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0006_alter_item_price_alter_item_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='status',
        ),
    ]
