# Generated by Django 4.2 on 2023-05-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0007_remove_buyer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='predopl',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='vydan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
