# Generated by Django 4.2 on 2023-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0008_remove_order_predopl_alter_buyer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
