# Generated by Django 4.2 on 2023-05-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0009_alter_tovar_name_alter_tovar_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.order')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uchet.supplier')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.tovar')),
            ],
        ),
    ]
