# Generated by Django 4.2 on 2023-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0013_remove_good_sklad_id_remove_sklad_good_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sklad_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sklad',
            name='good_id',
            field=models.IntegerField(default=0),
        ),
    ]
