# Generated by Django 4.2 on 2023-05-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0014_good_sklad_id_sklad_good_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='sklad_id',
            new_name='sklad_ref',
        ),
        migrations.RenameField(
            model_name='sklad',
            old_name='good_id',
            new_name='good_ref',
        ),
    ]
