# Generated by Django 4.2 on 2023-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0015_rename_sklad_id_good_sklad_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sklad_ref',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='good_ref',
        ),
        migrations.AddField(
            model_name='good',
            name='sklad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sklad',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
