# Generated by Django 4.2 on 2023-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0016_remove_good_sklad_ref_remove_sklad_good_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sklad',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='good',
        ),
        migrations.AddField(
            model_name='good',
            name='skladd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sklad',
            name='goodd',
            field=models.IntegerField(default=0),
        ),
    ]
