# Generated by Django 4.2 on 2023-05-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0017_remove_good_sklad_remove_sklad_good_good_skladd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='skladd',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='goodd',
        ),
        migrations.AddField(
            model_name='good',
            name='skladref',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sklad',
            name='goodref',
            field=models.IntegerField(default=0),
        ),
    ]
