# Generated by Django 4.2 on 2023-05-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0018_remove_good_skladd_remove_sklad_goodd_good_skladref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='tovar',
        ),
        migrations.DeleteModel(
            name='good',
        ),
        migrations.DeleteModel(
            name='sklad',
        ),
    ]
