# Generated by Django 4.2 on 2023-05-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0021_goodr_skladr_remove_sklad_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladr',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uchet.order'),
        ),
    ]
